name: Deploy Lambda Functions
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"

      - name: Create deployment packages
        run: |
          cd lambda
          for func in extract standardize; do
            echo "Creating package for $func function..."
            
            # Create fresh package directory
            rm -rf package
            mkdir -p package

            # Install dependencies with platform-specific binaries
            if [ "$func" = "extract" ]; then
              pip install --target ./package \
                  --platform manylinux2014_x86_64 \
                  --implementation cp \
                  --python-version 3.9 \
                  --only-binary=:all: \
                  pillow pytesseract
            else
              pip install --target ./package \
                  openai
            fi

            # Copy source file
            cp src/$func.py package/$func.py

            # Create zip file with correct name
            cd package
            if [ "$func" = "extract" ]; then
              zip -r ../function.zip .
            else
              zip -r ../${func}_function.zip .
            fi
            cd ..

            echo "Created zip file for $func"
            ls -lh *.zip
          done

      - name: Create Tesseract layer
        run: |
          cd lambda
          rm -rf lambda-layer
          mkdir -p lambda-layer

          docker run --rm -v $(pwd)/lambda-layer:/layer amazonlinux:2 \
            bash -c "
              set -ex
              
              echo '=== SYSTEM SETUP ==='
              amazon-linux-extras install epel -y
              yum clean all
              yum makecache
              yum update -y
              
              echo '=== INSTALLING PACKAGES ==='
              yum install -y which
              yum list available | grep tesseract
              yum install -y tesseract
              yum install -y libstdc++ libgomp libtiff libpng libjpeg leptonica
              
              echo '=== TESSERACT INSTALLATION INFO ==='
              command -v tesseract
              tesseract --version
              
              echo '=== PACKAGE FILES ==='
              rpm -ql tesseract
              
              echo '=== COPYING FILES ==='
              # Copy tesseract binary and verify
              mkdir -p /layer/bin
              cp -v /usr/bin/tesseract /layer/bin/
              chmod 755 /layer/bin/tesseract
              ls -l /layer/bin/tesseract

              # Copy tessdata files
              mkdir -p /layer/lib/tessdata
              cp -rv /usr/share/tesseract/tessdata/* /layer/lib/tessdata/
              ls -l /layer/lib/tessdata/
              
              echo '=== COPYING LIBRARIES ==='
              # Copy all required libraries
              ldd /usr/bin/tesseract \
                | grep -oP '/.*\.so[^ ]*' \
                | xargs -I{} cp -v {} /layer/lib/
              
              echo '=== VERIFYING LAYER CONTENTS ==='
              find /layer -type f -ls
              
              echo '=== TESTING TESSERACT ==='
              LD_LIBRARY_PATH=/layer/lib TESSDATA_PREFIX=/layer/lib/tessdata /layer/bin/tesseract --version
            "
          
          echo '=== FINAL LAYER CONTENTS ==='
          find lambda-layer -type f -ls
          
          echo '=== LAYER CONTENTS BEFORE ZIP ==='
          echo "== Full layer directory structure =="
          find lambda-layer -type f -ls
          
          echo "== Verifying critical files =="
          ls -l lambda-layer/opt/bin/tesseract
          ls -l lambda-layer/opt/lib/tessdata/eng.traineddata
          
          cd lambda-layer
          zip -r ../tesseract-layer.zip .
          cd ..
          
          echo '=== VERIFYING ZIP CONTENTS ==='
          unzip -l tesseract-layer.zip | grep -E "opt/bin/tesseract|opt/lib/tessdata"

      - name: Terraform Init
        run: |
          cd lambda/infrastructure
          terraform init -upgrade

      - name: Select Terraform Workspace
        run: |
          cd lambda/infrastructure
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform Plan
        id: terraform_plan
        run: |
          cd lambda/infrastructure
          terraform plan -out=tfplan \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"
        continue-on-error: true

      - name: Check Terraform Plan Exit Code
        run: |
          if [ -s lambda/infrastructure/tfplan ]; then
            echo "Terraform plan succeeded with changes."
            echo "apply_plan=true" >> $GITHUB_ENV
          else
            echo "No changes detected or plan failed."
            echo "apply_plan=false" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
        if: env.apply_plan == 'true'
        run: |
          cd lambda/infrastructure
          terraform apply -auto-approve tfplan
