name: Deploy Lambda Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"

      - name: Create deployment packages
        run: |
          cd lambda
          for func in extract standardize; do
            echo "Creating package for $func function..."
            
            # Create fresh package directory
            rm -rf package
            mkdir -p package

            # Install dependencies with platform-specific binaries
            pip install --target ./package \
                --platform manylinux2014_x86_64 \
                --implementation cp \
                --python-version 3.9 \
                --only-binary=:all: \
                pillow pytesseract

            # Copy source file
            cp src/$func.py package/$func.py

            # Create zip file
            cd package
            zip -r ../${func}_function.zip .
            cd ..

            echo "Created ${func}_function.zip"
            ls -lh ${func}_function.zip
          done

      - name: Create Tesseract layer
        run: |
          cd lambda
          mkdir -p lambda-layer/python
          mkdir -p lambda-layer/lib
          
          docker run --rm -v $(pwd)/lambda-layer:/layer amazonlinux:2 \
            bash -c "
              yum install -y tesseract tesseract-langpack-eng
              yum install -y libstdc++ libgomp libtiff libpng libjpeg
              
              mkdir -p /layer/lib
              cp /usr/bin/tesseract /layer/lib/
              cp -r /usr/share/tesseract /layer/lib/
              cp -r /usr/lib64/libtesseract* /layer/lib/
              cp -r /usr/lib64/liblept* /layer/lib/
              cp -r /usr/lib64/libpng* /layer/lib/
              cp -r /usr/lib64/libtiff* /layer/lib/
              cp -r /usr/lib64/libjpeg* /layer/lib/
              cp -r /usr/lib64/libwebp* /layer/lib/
              cp -r /usr/lib64/libgomp* /layer/lib/
              cp -r /usr/lib64/libstdc++* /layer/lib/
              
              chmod 755 /layer/lib/*
            "
          
          cd lambda-layer
          zip -r ../tesseract-layer.zip .
          cd ..

      - name: Terraform Init
        run: |
          cd lambda/infrastructure
          terraform init -upgrade

      - name: Terraform Apply
        run: |
          cd lambda/infrastructure
          terraform apply -auto-approve \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"
